# Generated by Django 4.1.3 on 2022-12-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_id_curso'),
        ('turma', '0003_alter_turma_horario_turmaaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
    ]
